mongo_db:
  image: mongo:3.0
  ports:
    - "27017:27017"
    - "28017:28017"
  command: --smallfiles

mongo_dashboard:
  image: mongo-express
  links:
    - mongo_db
  ports:
    - '8081:8081'
  environment:
    ME_CONFIG_MONGODB_SERVER: 'mongo_db'
    ME_CONFIG_MONGODB_PORT: 27017

api:
  build: .
  ports:
    - '8080:8080'
  volumes:
    - ./app:/usr/local/mean/app
  links:
    - mongo_db
  entrypoint: /usr/local/mean/wait-for-it.sh mongo_db:27017 -s -- nodemon -L app/server.js
  environment:
    DBURI: 'mongodb://mongo_db:27017/DevOps'